# Generated by Django 4.1.3 on 2023-09-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
