# Generated by Django 4.1.3 on 2023-09-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_likes_user_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
    ]
